import type { LearningFigureSpec } from '../types'

const civ = (section: string) => `https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=CIV&sectionNum=${section}.`
const trustGuide = 'https://www.dre.ca.gov/files/pdf/re13.pdf'
const closing = 'https://www.consumerfinance.gov/owning-a-home/closing-disclosure/'

export const documentFigures: LearningFigureSpec[] = [
  {
    id: 'exp-document-grant-deed', lessonSlug: 'transfer-deeds-and-vesting', afterSection: 'essential-elements-and-intent',
    kind: 'document', title: 'Read the operative parts of a deed',
    objective: 'Identify the conveying party, receiving party, interest, property description, and signature in a fictional deed excerpt.',
    sourceUrls: [civ('1092'), civ('1091')],
    documentTitle: 'Grant deed / Selected terms',
    context: 'All names and map references are fictional. This excerpt omits execution, acknowledgment, delivery, and recording requirements.',
    fields: [
      { label: 'Grantor', value: 'Alex Morgan', annotation: 'This person conveys the described interest. Match the name and authority to the ownership records.' },
      { label: 'Operative words and grantee', value: 'Grants to Casey Lee an undivided one-half interest', annotation: 'The words identify both the recipient and the fraction conveyed. The transfer is not the whole fee interest.' },
      { label: 'Property', value: 'Lot 12, Example Tract; fictional Map Book 8, page 20, Example County, California', annotation: 'The description points to an identified mapped lot. It is not a description of only the north half of that lot.' },
      { label: 'Signature', value: 'Alex Morgan, as grantor', annotation: 'A signature and an adequate description do not, by themselves, establish effective delivery and acceptance.' },
    ],
    conclusion: 'If validly delivered and accepted, Casey receives an undivided interest throughout the described lot, not a physically carved-out half.',
    caption: 'Original educational drafting excerpt. It is not a recordable form or an opinion about a real title.',
  },
  {
    id: 'exp-document-reserved-estate', lessonSlug: 'transfer-deeds-and-vesting', afterSection: 'a-description-can-transfer-less-than-the-buyer-expects',
    kind: 'document', title: 'A reservation changes what the deed conveys',
    objective: 'Read an express life-estate reservation instead of assuming an unrestricted fee-simple transfer.',
    sourceUrls: [civ('1105')], documentTitle: 'Conveyance / Reservation excerpt',
    context: 'Assume valid creation, delivery, and acceptance, with no other interests or restrictions.',
    fields: [
      { label: 'Grantor', value: 'Devin, the current fee owner', annotation: 'Devin begins with the ownership interest being divided by the grant.' },
      { label: 'Grantee', value: 'Emery', annotation: 'Emery receives the interest defined by the complete grant, including its reservation.' },
      { label: 'Reservation', value: 'Devin reserves a life estate measured by Devin\'s life.', annotation: 'The express lesser-estate language changes the default reading. Devin retains present possession under that life estate.' },
      { label: 'Interest conveyed', value: 'The remainder to Emery', annotation: 'Emery has a future possessory interest. Devin\'s death ends the stated measuring life; it does not create Emery\'s interest for the first time.' },
    ],
    conclusion: 'Read the reservation before choosing the interest acquired. A familiar deed heading does not override its operative terms.',
    caption: 'A simplified reservation example, not a complete deed. The grant\'s language determines the estate intended to pass.',
  },
  {
    id: 'exp-document-title-report', lessonSlug: 'transfer-title-and-escrow', afterSection: 'read-a-title-problem-in-layers',
    kind: 'document', title: 'Separate a title requirement from a continuing exception',
    objective: 'Classify ownership, land identity, payoff requirements, and continuing exceptions in a preliminary title excerpt.',
    sourceUrls: ['https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=INS&sectionNum=12340.11.'],
    documentTitle: 'Preliminary title report / Selected items',
    context: 'Fictional report for a proposed purchase of Lot 12 only. No insurance policy has been issued.',
    fields: [
      { label: 'Vesting', value: 'Alex and Blair, as tenants in common', annotation: 'Check authority to convey both ownership interests. One name in a negotiation is not authority from both owners.' },
      { label: 'Land described', value: 'Lots 12 and 13, Example Tract', annotation: 'This differs from the one-lot purchase. Reconcile the intended insured land and the conveyance before closing.' },
      { label: 'Requirement', value: 'Obtain payoff and reconveyance for the existing deed of trust.', annotation: 'This is a closing clearance item under the stated transaction, not a promise to let the old loan remain.' },
      { label: 'Exception', value: 'Recorded utility easement across the rear 10 feet.', annotation: 'An accepted continuing easement may remain excluded from coverage. Read the underlying easement and its effect on intended use.' },
    ],
    conclusion: 'An offer to insure subject to listed matters is not a guarantee of actual title or of the buyer\'s proposed use.',
    caption: 'Original report excerpt. Actual schedules, requirements, and coverage must be read together.',
  },
  {
    id: 'exp-document-loan-estimate', lessonSlug: 'financing-credit-law-originators', afterSection: 'loan-estimate-and-closing-disclosure',
    kind: 'document', title: 'Three figures on a loan estimate answer different questions',
    objective: 'Distinguish loan amount, monthly housing payment, and additional cash needed to close.',
    sourceUrls: ['https://www.consumerfinance.gov/owning-a-home/loan-estimate/'],
    documentTitle: 'Loan Estimate / Teaching excerpt',
    context: 'A fictional $600,000 purchase with a $480,000 loan. Costs and payments below are stipulated estimates, not a loan offer.',
    fields: [
      { label: 'Loan amount', value: '$480,000', annotation: 'This finances 80% of the stated price. It is neither the price nor the amount the buyer must bring.' },
      { label: 'Estimated total monthly payment', value: '$3,550', annotation: 'Suppose $2,850 is principal and interest and $700 is escrowed taxes and insurance. These components serve different purposes.' },
      { label: 'Estimated closing costs', value: '$12,000', annotation: 'Closing costs are distinct from the $120,000 down payment. They do not replace that contribution.' },
      { label: 'Estimated cash to close', value: '$112,000', annotation: 'With a $20,000 deposit already paid and no other credits: $120,000 + $12,000 - $20,000.' },
    ],
    conclusion: 'The deposit reduces the additional cash due; it does not reduce the contractual loan balance.',
    caption: 'Original instructional excerpt, not the CFPB form. Figures are fictional and simplified.',
  },
  {
    id: 'exp-document-closing-cash', lessonSlug: 'transfer-title-and-escrow', afterSection: 'reconcile-a-simple-closing-statement',
    kind: 'document', title: 'Read the buyer\'s cash-to-close reconciliation',
    objective: 'Reconcile price, financing, deposit, costs, and seller credits without counting the deposit twice.',
    sourceUrls: [closing], documentTitle: 'Closing statement / Buyer worksheet',
    context: 'A simplified fictional closing with no tax impounds, prepaid interest, or other adjustments beyond those shown.',
    fields: [
      { label: 'Price less new loan', value: '$800,000 - $600,000 = $200,000', annotation: 'This is the buyer\'s price contribution before credit for the deposit already supplied.' },
      { label: 'Deposit already held', value: '$24,000 credit', annotation: 'Subtract this paid amount. Adding it would require the buyer to supply it twice.' },
      { label: 'Buyer closing costs', value: '$9,000 charge', annotation: 'Add the costs allocated to the buyer. They are separate from the sale price.' },
      { label: 'Seller cost credit', value: '$4,000 credit', annotation: 'Apply the agreed permitted credit. It reduces the buyer\'s cash requirement, not the stated sale price.' },
    ],
    conclusion: 'Additional cash: $200,000 - $24,000 + $9,000 - $4,000 = $181,000.',
    caption: 'Trace each credit to its source. A buyer deposit, lender proceeds, and seller concession are not interchangeable.',
  },
  {
    id: 'exp-ledger-seller-closing', lessonSlug: 'transfer-title-and-escrow', afterSection: 'follow-the-closing-sequence',
    kind: 'ledger', title: 'Follow sale proceeds to their destinations',
    objective: 'Reconcile seller proceeds while distinguishing payments to creditors from buyer-seller prorations.',
    sourceUrls: [closing], account: 'Seller proceeds / Simplified closing', openingBalance: 0,
    entries: [
      { label: 'Sale proceeds received', received: 800000, paid: 0, balance: 800000 },
      { label: 'Existing loan payoff', received: 0, paid: 300000, balance: 500000 },
      { label: 'Seller closing charges', received: 0, paid: 40000, balance: 460000 },
      { label: 'Proration credited to buyer', received: 0, paid: 900, balance: 459100 },
    ],
    conclusion: 'Net proceeds are $459,100 under these assumptions. The $300,000 payoff goes to the creditor, not to the buyer.',
    caption: 'The running balance traces fictional cash disbursements. It does not calculate taxable gain.',
  },
  {
    id: 'exp-ledger-owner-reserve', lessonSlug: 'practice-trust-funds', afterSection: 'three-records-should-tell-one-story',
    kind: 'ledger', title: 'An owner ledger explains whose money remains',
    objective: 'Read a beneficiary ledger and calculate the owner\'s remaining reserve after authorized transactions.',
    sourceUrls: [trustGuide], account: 'Owner A / Separate beneficiary record', openingBalance: 6000,
    entries: [
      { label: 'Collected rent', received: 2500, paid: 0, balance: 8500 },
      { label: 'Authorized plumbing repair', received: 0, paid: 500, balance: 8000 },
      { label: 'Earned management fee', received: 0, paid: 200, balance: 7800 },
      { label: 'Distribution to owner', received: 0, paid: 6800, balance: 1000 },
    ],
    conclusion: 'The $1,000 balance belongs to Owner A. Other owners need separate records even when funds share one trust bank account.',
    caption: 'Amounts, authorization, collection, and fee entitlement are stipulated. Reconcile this record with the account control and adjusted bank balance.',
  },
  {
    id: 'exp-ledger-beneficiary-shortage', lessonSlug: 'practice-trust-funds', afterSection: 'diagnose-shortages-without-hiding-them',
    kind: 'ledger', title: 'A negative owner balance exposes the shortage',
    objective: 'Detect a beneficiary shortage even when the shared bank account remains positive.',
    sourceUrls: [trustGuide], account: 'Owner B / Improper over-disbursement', openingBalance: 3000,
    entries: [
      { label: 'Repair payment for B', received: 0, paid: 4000, balance: -1000 },
    ],
    conclusion: 'If Owner A is still owed $9,000 and the bank now holds $8,000, the $1,000 deficit is a shortage, not a permissible loan from A.',
    caption: 'Assume no prior written consent from all fund owners. This depicts a prohibited use of another beneficiary\'s funds; netting the negative and positive ledgers conceals the shortage.',
  },
  {
    id: 'exp-timeline-recording-notice', lessonSlug: 'transfer-deeds-and-vesting', afterSection: 'actual-notice-changes-the-recording-problem',
    kind: 'timeline', title: 'First to record can still lose priority',
    objective: 'Apply the good-faith and notice conditions instead of treating recording as a pure race.',
    sourceUrls: [civ('1214')], premise: 'Assume two otherwise valid deeds of the same property, valuable consideration, and no other priority issues.',
    events: [
      { when: 'Monday', label: 'First deed delivered', detail: 'Buyer One accepts the seller\'s deed but does not record it.' },
      { when: 'Tuesday', label: 'Buyer Two learns of that deed', detail: 'Buyer Two has actual knowledge before acquiring the competing interest.' },
      { when: 'Wednesday', label: 'Buyer Two pays and records', detail: 'The later deed reaches the recorder first, but the prior knowledge defeats the stated good-faith-without-notice premise.' },
    ],
    conclusion: 'Change the notice fact, not just the recording date, when testing whether a later purchaser qualifies for protection.',
    caption: 'The timeline isolates actual notice. Real disputes can also involve constructive or inquiry notice and other facts.',
  },
  {
    id: 'exp-document-unbanked-receipt', lessonSlug: 'practice-trust-funds', afterSection: 'follow-one-payment-from-receipt-to-release',
    kind: 'document', title: 'A check delivered directly to escrow still needs a record',
    objective: 'Identify receipt and disposition evidence when entrusted funds never enter the broker\'s bank account.',
    sourceUrls: [trustGuide], documentTitle: 'Trust receipt and delivery log / Excerpt',
    context: 'Assume the broker directed immediate delivery of this buyer check to the named neutral escrow.',
    fields: [
      { label: 'Received', value: 'Monday, 10:00 a.m. / $8,000 buyer check', annotation: 'Record receipt even though the check is payable to escrow rather than to the brokerage.' },
      { label: 'Purpose', value: 'Buyer C / Example purchase deposit', annotation: 'Identify the transaction and whose value is being handled.' },
      { label: 'Disposition', value: 'Delivered to neutral escrow Monday, 11:00 a.m.', annotation: 'The salesperson follows the broker\'s direction immediately, without a personal three-day holding period.' },
      { label: 'Evidence', value: 'Escrow delivery receipt attached', annotation: 'The supporting receipt explains the money\'s destination. No brokerage-bank deposit does not mean no trust record.' },
    ],
    conclusion: 'Custody creates an accounting trail even when the account control record never receives a bank-deposit entry.',
    caption: 'Fictional log excerpt. It teaches receipt and disposition, not a complete regulatory record format.',
  },
]
