import type { LearningFigureSpec } from '../types'

const code = (law: string, section: string) =>
  `https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=${law}&sectionNum=${section}.`
const title = 'https://www.dre.ca.gov/files/pdf/refbook/ref05.pdf'
const classification =
  'https://leginfo.legislature.ca.gov/faces/codes_displayText.xhtml?division=2.&chapter=&part=1.&lawCode=CIV&title=1.'
const descriptions =
  'https://www.govinfo.gov/content/pkg/GOVPUB-I53-PURL-gpo62570/pdf/GOVPUB-I53-PURL-gpo62570.pdf'
const water = 'https://www.waterboards.ca.gov/waterrights/board_info/faqs.html'

export const ownershipApplicationFigures: LearningFigureSpec[] = [
  {
    id: 'exp-ownership-showing-inclusion-register',
    lessonSlug: 'ownership-property-rights',
    afterSection: 'worked-scenario-the-equipment-at-closing',
    title: 'Read three different transfer instructions',
    objective: 'Apply an exclusion, an inclusion, and a third-party ownership limit without treating attachment as the complete agreement.',
    sourceUrls: [classification, title], kind: 'document',
    documentTitle: 'Fictional sale inclusion register',
    context: 'Assume valid agreed terms and verified third-party ownership; this is not a complete contract.',
    fields: [
      { label: 'Dining light', value: 'Seller retains; replace before closing', annotation: 'An ordinarily attached fixture has a specific negotiated exclusion and replacement obligation.' },
      { label: 'Rolling kitchen cart', value: 'Included in the sale', annotation: 'The movable item is included by agreement; inclusion does not turn every cart into real property.' },
      { label: 'Rooftop panels', value: 'Equipment lessor owns them', annotation: 'A seller cannot convey the lessor\'s equipment as seller-owned merely because the panels are attached.' },
      { label: 'Solar contract', value: 'Transfer approval unresolved', annotation: 'Verify the separate contractual process before representing that the buyer has assumed the arrangement.' },
    ],
    conclusion: 'Classification, agreed transfer terms, and ownership authority are separate checks.',
    caption: 'Original instructional excerpt. Change only the cart inclusion to an exclusion and the bargain changes without changing the cart\'s physical classification.',
  },
  {
    id: 'exp-ownership-screen-mount-account',
    lessonSlug: 'ownership-property-rights', afterSection: 'compare-objects-by-function-and-agreement',
    title: 'One installation can contain three different assets',
    objective: 'Separate a physical device, its fitted attachment, and its associated service rights.',
    sourceUrls: [classification], kind: 'relationship',
    center: { label: 'Media installation', detail: 'Assume the screen stays under the sale agreement. What else has actually been transferred?' },
    nodes: [
      { label: 'Screen', connection: 'included object', detail: 'The identified seller-owned television is part of the bargain.' },
      { label: 'Wall mount', connection: 'attachment evidence', detail: 'Check the mount, wiring, restoration terms, and fixture analysis separately.' },
      { label: 'Streaming account', connection: 'separate contract', detail: 'The physical inclusion does not prove that a personal subscription can or will transfer.' },
    ],
    caption: 'Conceptual component map, not a wiring diagram. Replace the screen with a leased device and ownership becomes another independent condition.',
  },
  {
    id: 'exp-ownership-note-versus-building',
    lessonSlug: 'ownership-property-rights', afterSection: 'real-and-personal-property',
    title: 'Identify the asset the investor actually owns',
    objective: 'Distinguish a debt claim and corporate shares from direct ownership of the real estate supporting their value.',
    sourceUrls: [classification, title], kind: 'comparison',
    columns: [
      { label: 'Buyer of a secured note', points: ['Acquires the repayment claim and associated assigned security rights.', 'Does not receive ordinary possession of the borrower\'s house by buying the note.'] },
      { label: 'Buyer of company shares', points: ['Acquires an interest in the company.', 'The company still holds its building; the shares are not a deed to a particular office.'] },
      { label: 'Buyer under a property deed', points: ['Acquires the real-property interest actually conveyed.', 'Read retained estates, reservations, and existing burdens before calling it unrestricted ownership.'] },
    ],
    caption: 'All three investments can depend on real estate. Their economic connection to a building does not make their legal interests identical.',
  },
  {
    id: 'exp-ownership-trade-removal-conditions',
    lessonSlug: 'ownership-property-rights', afterSection: 'trade-fixtures-and-severance',
    title: 'Change the removal facts, not just the business label',
    objective: 'Apply the during-term, no-injury, and integral-part limits to tenant fixture removal.',
    sourceUrls: [code('CIV', '1019')], kind: 'decision',
    question: 'Assume tenant-installed trade equipment and no lease provision changing the statutory baseline. Which fact changes the removal analysis?',
    branches: [
      { label: 'Removable display rack; tenancy continues', detail: 'Removal leaves the premises uninjured and the rack is not an integral building component.', outcome: 'The stated facts support the statutory removal route.' },
      { label: 'Integrated structural installation', detail: 'Taking it out would damage the premises or remove an integral part.', outcome: 'Business purpose alone does not satisfy the removal conditions.' },
      { label: 'Tenant waits until the term ends', detail: 'No separate post-term removal right is established.', outcome: 'Do not assume section 1019 supplies an unlimited right to return and remove it.' },
    ],
    caption: 'The statute also addresses qualifying ornamental and domestic installations. This example isolates trade equipment, not every improvement a tenant could install.',
  },
  {
    id: 'exp-ownership-severance-permission-sequence',
    lessonSlug: 'ownership-property-rights', afterSection: 'crops-and-intended-removal',
    title: 'A movable result does not prove authorized removal',
    objective: 'Distinguish an object\'s changed classification from the legal authority to detach and sell it.',
    sourceUrls: [classification], kind: 'timeline',
    premise: 'An owner commissions lawful removal of an attached ornamental tree and sale of the resulting timber; no separate goods-to-be-severed arrangement is assumed before removal.',
    events: [
      { when: 'Before cutting', label: 'Rooted tree', detail: 'The attached tree ordinarily belongs to the realty.' },
      { when: 'Authority checked', label: 'Permission and restrictions', detail: 'Confirm who owns the tree and any applicable removal restrictions; attachment classification does not grant permission.' },
      { when: 'After lawful detachment', label: 'Timber', detail: 'The detached movable timber is personal property.' },
      { when: 'Changed fact', label: 'Unauthorized cutting', detail: 'Detachment can still make the timber movable while leaving a claim for the wrongful removal.' },
    ],
    conclusion: 'Severance describes a classification change, not immunity from a removal violation.',
    caption: 'A contract for crops or things agreed to be severed can receive the special sale treatment described in CIV 658 and 660; do not erase that exception.',
  },
  {
    id: 'exp-ownership-fixture-price-distraction',
    lessonSlug: 'ownership-property-rights', afterSection: 'how-an-object-becomes-a-fixture',
    title: 'Price does not decide permanence',
    objective: 'Discard purchase price as a standalone fixture test and identify stronger objective evidence.',
    sourceUrls: [classification], kind: 'comparison',
    columns: [
      { label: '$8,000 freestanding sculpture', points: ['Rests as movable decoration; no special attachment is stated.', 'Its high price does not establish that it became part of the realty.'] },
      { label: '$80 hardwired doorbell', points: ['Permanently wired into the building\'s functioning system.', 'Its low price does not negate the attachment evidence.'] },
      { label: 'Change only the agreement', points: ['An express lawful inclusion or exclusion can define the parties\' bargain.', 'Still check ownership and third-party rights; a price tag supplies neither.'] },
    ],
    caption: 'These facts teach evidentiary weight, not an automatic classification for every sculpture or doorbell. Adaptation, objective intent, relationship, and terms still matter.',
  },
  {
    id: 'exp-ownership-solar-obligation-comparison',
    lessonSlug: 'ownership-property-rights', afterSection: 'resolve-the-scope-before-pricing-the-bargain',
    title: 'Equal panel counts can conceal unequal obligations',
    objective: 'Identify a separate equipment-payment commitment without treating it as an appraisal adjustment or transferred ownership.',
    sourceUrls: [classification, title], kind: 'document',
    documentTitle: 'Fictional solar comparison worksheet',
    context: 'Two homes have the same asking price and panel count. These are stipulated contract facts, not market quotations.',
    fields: [
      { label: 'Home A', value: 'Seller-owned panels; included', annotation: 'Verify seller ownership and any lien clearance before treating ownership as transferred.' },
      { label: 'Home B', value: 'Separate equipment lease', annotation: 'The building sale alone does not transfer the equipment lessor\'s ownership.' },
      { label: 'Stated remaining payments', value: '$150 x 24 months = $3,600', annotation: 'This is nominal contract outlay if the buyer validly assumes these terms, ignoring other charges.' },
      { label: 'Unresolved condition', value: 'Lessor transfer approval', annotation: 'Approval and the complete contract must be checked before representing the arrangement as assumed.' },
    ],
    conclusion: '$3,600 identifies a stipulated obligation, not an automatic $3,600 difference in market value.',
    caption: 'Original comparison excerpt. Financing, performance guarantees, energy savings, and equipment condition are deliberately not valued here.',
  },
  {
    id: 'exp-ownership-reserved-vertical-rights',
    lessonSlug: 'ownership-property-rights', afterSection: 'separate-a-right-from-permission-and-possession',
    title: 'Buying the surface does not settle the subsurface',
    objective: 'Trace an expressly reserved mineral interest and distinguish it from the surface estate and any access authority.',
    sourceUrls: [classification, title], kind: 'document',
    documentTitle: 'Fictional reservation review',
    context: 'Assume an effective conveyance with a valid express mineral reservation. No extraction or access right is assumed beyond the actual instruments and law.',
    fields: [
      { label: 'Buyer\'s acquired interest', value: 'Described surface estate', annotation: 'Physical ownership of the parcel surface is the starting interest, not proof of every extractive right.' },
      { label: 'Reservation', value: 'Seller retains identified mineral interest', annotation: 'Read the full reservation rather than an advertisement calling the parcel fee owned.' },
      { label: 'Proposed drilling access', value: 'Not resolved by this excerpt', annotation: 'Mineral ownership and the scope of surface entry require their own document and legal analysis.' },
    ],
    conclusion: 'An underground asset, the right to extract it, and the right to enter the surface are connected but distinct questions.',
    caption: 'Original teaching excerpt, not a mineral deed or legal description. No unlimited subsurface or airspace use is represented.',
  },
  {
    id: 'exp-ownership-estate-vesting-possession',
    lessonSlug: 'ownership-estates-title', afterSection: 'ask-two-different-ownership-questions',
    title: 'Read estate, vesting, and possession on separate lines',
    objective: 'Extract three compatible ownership facts from one transaction without confusing duration, co-ownership, and occupancy.',
    sourceUrls: [title, 'https://www.dre.ca.gov/files/pdf/refbook/ref09.pdf'], kind: 'document',
    documentTitle: 'Fictional ownership summary',
    context: 'Assume valid title and a continuing lease; this is not a title opinion.',
    fields: [
      { label: 'Estate', value: 'Fee simple', annotation: 'Describes the ownership estate\'s duration and extent.' },
      { label: 'Vesting', value: 'Lee and River, tenants in common', annotation: 'Describes how the concurrent owners hold the estate.' },
      { label: 'Current occupant', value: 'Tenant under an unexpired lease', annotation: 'Present leasehold possession can coexist with the owners\' fee interests.' },
    ],
    conclusion: 'The tenant\'s key does not cancel fee title, and fee title does not automatically erase the lease.',
    caption: 'Changing the vesting to severalty changes the number or form of owners, not necessarily the estate\'s duration or the tenant\'s occupancy right.',
  },
  {
    id: 'exp-ownership-measuring-life-transfer',
    lessonSlug: 'ownership-estates-title', afterSection: 'follow-the-measuring-life-through-a-transfer',
    title: 'Follow the life named in the original grant',
    objective: 'Keep the measuring life unchanged when a life-estate holder transfers the interest to another person.',
    sourceUrls: [code('CIV', '1108')], kind: 'timeline',
    premise: 'Nora holds a valid estate measured by Luis\'s life and transfers her entire interest to Priya. Luis remains alive during the first three events.',
    events: [
      { when: 'Original grant', label: 'Luis is the measuring life', detail: 'Nora is the holder; Luis need not be the possessor.' },
      { when: 'Transfer to Priya', label: 'Holder changes', detail: 'Priya receives the transferable estate Nora has, not a newly created fee simple.' },
      { when: 'Nora later dies', label: 'Measuring life continues', detail: 'Nora\'s death does not end an estate defined by Luis\'s life.' },
      { when: 'Luis later dies', label: 'Stated life estate ends', detail: 'The future estate becomes possessory under the creating arrangement.' },
    ],
    conclusion: 'Change the original grant to Nora\'s life, and Nora\'s death now controls. The buyer\'s price never enlarges the estate.',
    caption: 'A grant purporting to convey more than the holder can transfer passes only the estate lawfully transferable under CIV 1108.',
  },
  {
    id: 'exp-ownership-lease-duration-diagnosis',
    lessonSlug: 'ownership-estates-title', afterSection: 'leasehold-estates',
    title: 'A short term can still be an estate for years',
    objective: 'Classify tenancy duration from the ending and renewal provisions rather than the document title.',
    sourceUrls: [title, 'https://www.dre.ca.gov/files/pdf/refbook/ref09.pdf'], kind: 'decision',
    question: 'Assume valid arrangements and no facts altering their stated duration. Which provision controls?',
    branches: [
      { label: 'June 1 through August 31', detail: 'A defined three-month term with a stated end.', outcome: 'Estate for years, despite lasting less than a year.' },
      { label: 'Renews monthly until lawfully ended', detail: 'No fixed final month is stated.', outcome: 'Periodic tenancy; legal termination requirements remain separate.' },
      { label: 'Former right ended; occupant remains', detail: 'The owner has not consented to continued occupancy.', outcome: 'Tenancy at sufferance in the stated case, not permission for a lockout.' },
    ],
    caption: 'A heading reading Rental Agreement does not answer these questions. Consent and later conduct can change the analysis of an actual holdover.',
  },
  {
    id: 'exp-ownership-partial-joint-severance',
    lessonSlug: 'ownership-estates-title', afterSection: 'one-owner-or-concurrent-owners',
    title: 'One transfer need not sever everyone\'s survivorship',
    objective: 'Follow a three-owner joint tenancy through one owner\'s transfer and a remaining joint tenant\'s later death.',
    sourceUrls: [title, code('CIV', '683')], kind: 'timeline',
    premise: 'Avery, Blake, and Cameron hold equal joint interests. Assume an effective permitted transfer, no other severance, and no competing claims.',
    events: [
      { when: 'Initially', label: 'Three equal joint interests', detail: 'Each holds one-third under the joint tenancy.' },
      { when: 'Avery transfers to Drew', label: 'Drew takes one-third', detail: 'Drew holds that share as tenant in common; Blake and Cameron retain survivorship between their remaining shares.' },
      { when: 'Blake later dies', label: 'Cameron holds two-thirds', detail: 'The surviving joint relationship concerns the two-thirds block. Drew\'s one-third is unaffected.' },
    ],
    conclusion: 'Do not give Cameron the whole property or divide Blake\'s former share among every surviving title holder.',
    caption: 'This isolates partial severance. Written agreements, creditor claims, statutory procedure, and later transactions can add separate issues.',
  },
  {
    id: 'exp-ownership-community-source-of-acquisition',
    lessonSlug: 'ownership-estates-title', afterSection: 'community-property',
    title: 'Marriage date alone does not classify every acquisition',
    objective: 'Distinguish the ordinary community-property presumption from an individual gift or inheritance exception.',
    sourceUrls: [code('FAM', '760'), code('FAM', '770')], kind: 'decision',
    question: 'Assume California domicile and no transmutation, mixed-fund claim, or other special fact. How was this property acquired?',
    branches: [
      { label: 'Purchased during marriage with community earnings', detail: 'The ordinary acquisition rule is the relevant starting point.', outcome: 'Community-property analysis.' },
      { label: 'Inherited individually during marriage', detail: 'The acquisition is an individual inheritance, not a joint purchase with earnings.', outcome: 'Separate-property exception applies to the stated acquisition.' },
      { label: 'Owned before marriage', detail: 'Later marriage alone is the only changed fact.', outcome: 'Do not infer automatic conversion to community property.' },
    ],
    caption: 'Characterization is not a recommendation of vesting or a calculation of tax basis. Later contributions or agreements can require additional analysis.',
  },
  {
    id: 'exp-ownership-community-two-year-lease',
    lessonSlug: 'ownership-estates-title', afterSection: 'management-is-not-unilateral-conveyancing-authority',
    title: 'Collecting rent does not authorize every signature',
    objective: 'Apply the ordinary joint-execution rule to a community real-property lease longer than one year.',
    sourceUrls: [code('FAM', '1102')], kind: 'document',
    documentTitle: 'Fictional lease authority check',
    context: 'Assume established community real property, no statutory exception, and no authorized agent for the absent spouse.',
    fields: [
      { label: 'Usual manager', value: 'One spouse collects monthly rent', annotation: 'Routine operational activity does not establish authority to sign for both spouses.' },
      { label: 'Proposed term', value: 'Two years', annotation: 'The proposed lease exceeds the statute\'s one-year threshold.' },
      { label: 'Execution presented', value: 'Only the managing spouse signs', annotation: 'Address required joinder or duly authorized representation; do not assume routine management supplies it.' },
    ],
    conclusion: 'Identify the property, proposed act, and authorized signers before treating execution as complete.',
    caption: 'This does not label every one-signature document automatically void. Characterization, statutory exceptions, and remedies require their own analysis.',
  },
  {
    id: 'exp-ownership-condominium-patio-boundaries',
    lessonSlug: 'ownership-estates-title', afterSection: 'read-common-interest-ownership-documents-as-a-group',
    title: 'A private-use patio need not be separately owned',
    objective: 'Read distinct unit, common-area, and exclusive-use rights from stipulated condominium documents.',
    sourceUrls: [code('CIV', '4125'), title], kind: 'relationship',
    center: { label: 'Unit 8 purchase', detail: 'Assume the recorded plan and declaration establish the following three different interests.' },
    nodes: [
      { label: 'Interior unit', connection: 'separate interest', detail: 'The plan defines the separately owned space; the door number alone does not establish its legal boundary.' },
      { label: 'Shared courtyard', connection: 'common interest', detail: 'The purchaser has the stated undivided common-area interest, not an exclusive physical slice.' },
      { label: 'Enclosed patio', connection: 'exclusive use', detail: 'The declaration gives Unit 8 exclusive use of this common area. A fence does not convert that use right into separate fee ownership.' },
    ],
    caption: 'Conceptual location-and-rights map, not a condominium plan. Maintenance follows the governing documents and law, not automatically whichever party has exclusive use.',
  },
  {
    id: 'exp-ownership-coowner-net-before-fraction',
    lessonSlug: 'ownership-estates-title', afterSection: 'ownership-fractions-are-not-physical-boundaries',
    title: 'Allocate the agreed net pool, not the gross price',
    objective: 'Compute co-owner proceeds after stipulated common charges without treating deed percentages as a complete accounting.',
    sourceUrls: [title], kind: 'calculation',
    rows: [
      { label: 'Whole-property sale price', amount: 720000 },
      { label: 'Stipulated common loan payoff', amount: -240000 },
      { label: 'Agreed common closing costs', amount: -30000 },
    ],
    result: { label: 'Net pool to allocate', amount: 450000, detail: 'At agreed 60% / 40% shares: $270,000 and $180,000. Multiplying the gross price first ignores the common deductions.' },
    caption: 'Assume both co-owners agree to these allocations and no reimbursements, unequal liabilities, taxes, or other adjustments remain. This is not a minority-interest appraisal.',
  },
  {
    id: 'exp-ownership-access-not-parking',
    lessonSlug: 'ownership-encumbrances', afterSection: 'access-includes-scope-and-maintenance-questions',
    title: 'A route to the street is not a parking grant',
    objective: 'Locate the burdened access strip and identify a proposed use outside an expressly limited grant.',
    sourceUrls: [code('CIV', '801'), code('CIV', '806')], kind: 'parcel',
    extent: { width: 100, height: 200 }, unit: 'feet',
    areas: [
      { key: 'A', label: 'Rear parcel: benefited land', x: 0, y: 0, width: 100, height: 100, pattern: 'clear', description: 'The grant benefits this rear parcel by providing passage to the street.' },
      { key: 'B', label: 'Front parcel: burdened land', x: 0, y: 100, width: 100, height: 100, pattern: 'clear', labelAt: { x: 68, y: 150 }, description: 'The front owner retains fee ownership, including the area subject to the access right.' },
      { key: 'C', label: 'Twenty-foot access corridor', x: 0, y: 100, width: 20, height: 100, pattern: 'hatch', description: 'Assume the grant expressly permits passage and excludes parking. A parking bay drawn here does not expand that permission.' },
    ],
    lines: [{ label: 'Public street at the south boundary', from: { x: 0, y: 200 }, to: { x: 100, y: 200 }, style: 'solid' }],
    conclusion: 'The rear parcel benefits, the front parcel bears the route, and the document controls the permitted activity.',
    caption: 'Original fictional plan, north up, not a survey or complete easement description. Width, purpose, and exclusions are stipulated for this exercise.',
  },
  {
    id: 'exp-ownership-garage-boundary-intrusion',
    lessonSlug: 'ownership-encumbrances', afterSection: 'license-encroachment-and-adverse-possession',
    title: 'Locate the intrusion before deciding the legal remedy',
    objective: 'Measure a physical encroachment without concluding that its owner acquired title or an easement.',
    sourceUrls: [title], kind: 'parcel',
    extent: { width: 150, height: 100 }, unit: 'feet',
    areas: [
      { key: 'A', label: 'West lot', x: 0, y: 0, width: 100, height: 100, pattern: 'clear', labelAt: { x: 40, y: 50 }, description: 'Assume the controlling survey locates its east boundary at the 100-foot line.' },
      { key: 'B', label: 'East lot', x: 100, y: 0, width: 50, height: 100, pattern: 'clear', labelAt: { x: 130, y: 15 }, description: 'The neighbor owns this lot and built the garage shown as C.' },
      { key: 'C', label: 'Garage footprint', x: 90, y: 30, width: 30, height: 40, pattern: 'hatch', labelAt: { x: 108, y: 50 }, description: 'Ten feet of width extends into A for forty feet: 10 x 40 = 400 square feet of physical intrusion.' },
    ],
    lines: [{ label: 'Stipulated surveyed boundary', from: { x: 100, y: 0 }, to: { x: 100, y: 100 }, style: 'dashed', labelAt: { x: 100, y: 85 } }],
    conclusion: 'Four hundred square feet describes the overlap, not an automatic transfer of that land to the garage owner.',
    caption: 'Original fictional plan. Agreements, history, legal claims, and equitable remedies need separate investigation; a salesperson should not order removal or declare title from this drawing.',
  },
  {
    id: 'exp-ownership-road-maintenance-allocation',
    lessonSlug: 'ownership-encumbrances', afterSection: 'access-includes-scope-and-maintenance-questions',
    title: 'Three benefiting parcels need not pay equal thirds',
    objective: 'Apply an express maintenance allocation and distinguish it from the statutory fallback based on use.',
    sourceUrls: [code('CIV', '845')], kind: 'allocation', total: 9000,
    segments: [
      { label: 'Parcel A: agreed 70%', amount: 6300, detail: '$9,000 x 0.70 = $6,300' },
      { label: 'Parcel B: agreed 20%', amount: 1800, detail: '$9,000 x 0.20 = $1,800' },
      { label: 'Parcel C: agreed 10%', amount: 900, detail: '$9,000 x 0.10 = $900' },
    ],
    caption: 'Assume a valid agreement governs this repair. Without an agreement, CIV 845 generally allocates by use; neither three parcels nor equal lot sizes establishes equal use.',
  },
  {
    id: 'exp-ownership-permission-defeats-shortcut',
    lessonSlug: 'ownership-encumbrances', afterSection: 'permission-and-title-evidence-can-point-in-different-directions',
    title: 'Years of use do not erase the permission letter',
    objective: 'Identify why documented permission undermines the ordinary adversity element of a prescription claim.',
    sourceUrls: [title], kind: 'document',
    documentTitle: 'Fictional access history file',
    context: 'Assume the permission remained effective throughout the described use, with no later adverse claim or reliance-based right established.',
    fields: [
      { label: 'Owner letter', value: 'Neighbor may cross with permission', annotation: 'This explains why the use began and continued; it is evidence against adversity.' },
      { label: 'Vehicle photographs', value: 'Repeated crossings over many years', annotation: 'They show visible activity, not whether the activity was legally adverse.' },
      { label: 'Buyer inference', value: 'Long use guarantees a prescriptive easement', annotation: 'Duration alone cannot replace the missing adversity element.' },
    ],
    conclusion: 'Change permission to a supported adverse-use history and a different inquiry begins; an easement is still not automatically proved.',
    caption: 'Original evidence comparison. This does not decide every license, estoppel, necessity, or prescription claim from one document.',
  },
  {
    id: 'exp-ownership-easement-nonuse-release',
    lessonSlug: 'ownership-encumbrances', afterSection: 'creation-and-termination',
    title: 'An overgrown route and a release prove different things',
    objective: 'Distinguish visual nonuse from a legally effective termination of an express easement.',
    sourceUrls: [title], kind: 'timeline',
    premise: 'Assume a valid express driveway easement with no stated expiration, merger, or other terminating event until the final step.',
    events: [
      { when: 'Grant recorded', label: 'Documented access right', detail: 'The right exists within the scope of its creation.' },
      { when: 'Driveway becomes overgrown', label: 'Evidence of nonuse', detail: 'The physical condition alone does not establish that the express right ended.' },
      { when: 'Buyer orders title investigation', label: 'Read the creating and later records', detail: 'Do not replace the legal history with a photograph or a guess about abandonment.' },
      { when: 'Effective release established', label: 'Different legal event', detail: 'A valid release by the proper holder supplies a termination basis that nonuse alone did not.' },
    ],
    conclusion: 'Identify the legal event that ended the right, not merely the last time someone drove there.',
    caption: 'This express-easement case differs from a right arising solely by necessity, whose continued existence can depend on that necessity.',
  },
  {
    id: 'exp-ownership-pending-action-not-award',
    lessonSlug: 'ownership-encumbrances', afterSection: 'separate-notice-security-and-exemption',
    title: 'A recorded lawsuit notice is not a judgment',
    objective: 'Distinguish notice of a qualifying real-property claim from proof of ownership and from a secured debt.',
    sourceUrls: [code('CCP', '405.20'), title], kind: 'document',
    documentTitle: 'Fictional title-dispute register',
    context: 'Assume a properly recorded notice concerning a pending action asserting a qualifying real-property claim.',
    fields: [
      { label: 'Claim in litigation', value: 'Competing right to the parcel', annotation: 'The merits of that claim still require resolution.' },
      { label: 'Recorded notice', value: 'Lis pendens', annotation: 'Alerts a prospective purchaser to the pending real-property action.' },
      { label: 'Court determination', value: 'Not yet entered', annotation: 'Recording the notice did not itself award title or establish a final money judgment.' },
    ],
    conclusion: 'A buyer must address the unresolved claim, not assume that paying a loan automatically clears it.',
    caption: 'Original instructional record. Eligibility, service, recording, and expungement involve legal requirements beyond this identification exercise.',
  },
  {
    id: 'exp-ownership-subordination-distribution',
    lessonSlug: 'ownership-encumbrances', afterSection: 'follow-priority-rather-than-the-number-of-claims',
    title: 'Change priority and the shortfall changes hands',
    objective: 'Calculate the effect of valid subordination on a fixed distribution pool without inferring that any debt disappears.',
    sourceUrls: [title], kind: 'comparison',
    columns: [
      { label: 'Before the stated subordination', points: ['$360,000 is available after all superior charges and costs.', 'A $150,000 senior claim receives $150,000; the $300,000 junior claim receives the remaining $210,000.'] },
      { label: 'After valid agreed reversal', points: ['The $300,000 claim now receives $300,000 first.', 'The subordinated $150,000 claim receives $60,000 and has a $90,000 unpaid balance.'] },
      { label: 'What did not change', points: ['The available $360,000 and total $450,000 of claims.', 'Priority affects this distribution, not by itself the availability of a later deficiency remedy.'] },
    ],
    caption: 'Assume an effective subordination, no competing priority rules, and the stated pool. Equal sharing would ignore the priority facts in both versions.',
  },
  {
    id: 'exp-ownership-payoff-versus-reconveyance',
    lessonSlug: 'ownership-encumbrances', afterSection: 'satisfaction-and-the-recorded-release',
    title: 'Trace the loan clearance to the correct record',
    objective: 'Distinguish debt satisfaction, security release, and the seller\'s ownership conveyance.',
    sourceUrls: [code('CIV', '2941')], kind: 'process',
    steps: [
      { label: 'Identify the secured obligation', detail: 'Match the payoff instructions to the actual deed of trust and beneficiary; a similar loan number is not enough.' },
      { label: 'Establish satisfaction', detail: 'Confirm the obligation was paid as required. A payment receipt concerns the debt.' },
      { label: 'Verify the security release', detail: 'Obtain the appropriate full reconveyance or other legally sufficient release and verify the relevant record.' },
      { label: 'Keep unrelated instruments separate', detail: 'The seller\'s deed conveys ownership. An accepted driveway easement can remain after the old loan is discharged.' },
    ],
    caption: 'CIV 2941 assigns discharge and reconveyance responsibilities. This is a document-function sequence, not a substitute for its deadlines or a title-clearance opinion.',
  },
  {
    id: 'exp-ownership-parcel-identity-mismatch',
    lessonSlug: 'ownership-legal-descriptions', afterSection: 'identity-before-arithmetic',
    title: 'One address can conceal two different property scopes',
    objective: 'Detect a mismatch between the land advertised and the land described for conveyance.',
    sourceUrls: [descriptions], kind: 'document',
    documentTitle: 'Fictional land-identity cross-check',
    context: 'Every name and recording reference is illustrative; none identifies a real parcel.',
    fields: [
      { label: 'Marketing brochure', value: 'House and adjoining garden lot', annotation: 'Describes two areas the buyer expects, without establishing their legal identity.' },
      { label: 'Draft conveyance', value: 'Lot 7, Example Map only', annotation: 'The garden is assumed to lie on separately identified Lot 8, which is not included in this draft.' },
      { label: 'Street address', value: 'One address used for both areas', annotation: 'A shared mailing label does not add the omitted legal lot to the conveyance.' },
      { label: 'Required reconciliation', value: 'Match the agreement, description, and map', annotation: 'Resolve whether Lot 8 is part of the bargain before calculating the acreage conveyed.' },
    ],
    conclusion: 'A correct area calculation for the wrong described land is still the wrong transaction answer.',
    caption: 'Original document comparison. An APN, street address, legal lot, and development site need not describe the same grouping of land.',
  },
  {
    id: 'exp-ownership-traverse-does-not-close',
    lessonSlug: 'ownership-legal-descriptions', afterSection: 'metes-and-bounds',
    title: 'Opposite directions do not guarantee a closed traverse',
    objective: 'Identify a ten-foot closure discrepancy in cardinal-direction calls before treating them as a complete rectangular boundary.',
    sourceUrls: [descriptions, code('BPC', '8726')], kind: 'document',
    documentTitle: 'Fictional boundary-call check',
    context: 'Cardinal directions on a flat exercise plane, with an identified point of beginning; not a survey computation for an actual parcel.',
    fields: [
      { label: 'First two calls', value: 'East 120 feet; south 80 feet', annotation: 'Move 120 feet east and 80 feet south of the starting point.' },
      { label: 'Next two calls', value: 'West 110 feet; north 80 feet', annotation: 'North-south movement cancels, but only 110 of the 120 eastward feet are reversed.' },
      { label: 'Final position', value: '10 feet east of the beginning', annotation: 'The stated calls do not close. Do not silently change a distance to make a rectangle.' },
      { label: 'Next step', value: 'Reconcile controlling description and survey evidence', annotation: 'A salesperson identifies the discrepancy and obtains qualified assistance.' },
    ],
    conclusion: 'East-west balance is 120 - 110 = 10 feet; a closure problem exists before any area formula is chosen.',
    caption: 'Changing the west call to 120 feet closes this simplified traverse, but correction of a real description requires more than an arithmetic guess.',
  },
  {
    id: 'exp-ownership-nested-quarter-location',
    lessonSlug: 'ownership-legal-descriptions', afterSection: 'government-rectangular-survey',
    title: 'Locate the northeast quarter inside the southwest quarter',
    objective: 'Read nested compass fractions from the whole section inward without selecting the northeast quarter of the entire section.',
    sourceUrls: [descriptions], kind: 'parcel',
    extent: { width: 1, height: 1 }, unit: 'miles',
    areas: [
      { key: 'A', label: 'Nominal whole section', x: 0, y: 0, width: 1, height: 1, pattern: 'clear', labelAt: { x: 0.72, y: 0.25 }, description: 'Start with 640 nominal acres. North is up and east is right.' },
      { key: 'B', label: 'Southwest quarter', x: 0, y: 0.5, width: 0.5, height: 0.5, pattern: 'hatch', labelAt: { x: 0.12, y: 0.86 }, description: 'First select the lower-left quarter: 640 / 4 = 160 acres.' },
      { key: 'C', label: 'Northeast quarter of B', x: 0.25, y: 0.5, width: 0.25, height: 0.25, pattern: 'solid', description: 'Then select the upper-right quarter inside B: 160 / 4 = 40 acres.' },
    ],
    conclusion: 'The described forty acres lies inside the southwest quarter, not at the northeast corner of the whole section.',
    caption: 'Original idealized survey-system diagram. Actual government lots and corrected surveys can have irregular acreage; nominal fractions do not override official evidence.',
  },
  {
    id: 'exp-ownership-overlap-double-count',
    lessonSlug: 'ownership-legal-descriptions', afterSection: 'keep-nested-fractions-and-added-parcels-distinct',
    title: 'Mentioning the same land twice does not add acreage',
    objective: 'Distinguish the union of overlapping described areas from addition of nonoverlapping parcels.',
    sourceUrls: [descriptions], kind: 'comparison',
    columns: [
      { label: 'Nested pieces', points: ['A quarter-section is 160 nominal acres.', 'Its northeast quarter is 40 acres already inside those 160; counting both does not create 200 acres.'] },
      { label: 'Separate nonoverlapping pieces', points: ['West half of the southeast quarter: 80 acres.', 'Northeast quarter of that southeast quarter: 40 acres; these two pieces total 120 acres.'] },
      { label: 'Operation to choose', points: ['Multiply fractions connected by "of" to measure each nested piece.', 'Add only after checking whether the described pieces overlap.'] },
    ],
    caption: 'Assume regular 640-acre sections. This compares sets of land, not the sufficiency of an actual deed; redundant or conflicting descriptions require clarification.',
  },
  {
    id: 'exp-ownership-half-area-not-half-frontage',
    lessonSlug: 'ownership-legal-descriptions', afterSection: 'worked-scenario-one-parcel-two-pricing-methods',
    title: 'Half the area can have none of the street frontage',
    objective: 'Determine frontage from the orientation of a proposed division instead of halving it mechanically with area.',
    sourceUrls: [descriptions], kind: 'parcel',
    extent: { width: 100, height: 200 }, unit: 'feet',
    areas: [
      { key: 'A', label: 'North half', x: 0, y: 0, width: 100, height: 100, pattern: 'hatch', description: '10,000 square feet, but no direct boundary along the illustrated south street.' },
      { key: 'B', label: 'South half', x: 0, y: 100, width: 100, height: 100, pattern: 'clear', description: 'Also 10,000 square feet; it retains all 100 feet along this street.' },
    ],
    lines: [{ label: 'Only street frontage in this exercise', from: { x: 0, y: 200 }, to: { x: 100, y: 200 }, style: 'solid' }],
    conclusion: 'At a stipulated $900 per street-front foot, the original 100-foot frontage indicates $90,000, not two automatic $45,000 frontage allocations.',
    caption: 'Original proposed-division sketch, not an approved subdivision. Access to the north piece requires separate inquiry; zero direct frontage does not itself decide all legal access rights.',
  },
  {
    id: 'exp-ownership-setback-coverage-envelope',
    lessonSlug: 'ownership-legal-descriptions', afterSection: 'compute-a-building-envelope-without-changing-ownership-acreage',
    title: 'A footprint can fit the setbacks and fail coverage',
    objective: 'Compare total lot area, a geometric setback envelope, and a separate building-coverage ceiling.',
    sourceUrls: [descriptions], kind: 'parcel',
    extent: { width: 100, height: 150 }, unit: 'feet',
    areas: [
      { key: 'A', label: 'Entire owned lot', x: 0, y: 0, width: 100, height: 150, pattern: 'clear', labelAt: { x: 50, y: 142 }, description: '100 x 150 = 15,000 square feet. Assume the street is at the south edge.' },
      { key: 'B', label: 'Setback envelope', x: 10, y: 15, width: 80, height: 115, pattern: 'hatch', labelAt: { x: 50, y: 24 }, description: 'Stipulated sides 10 feet, rear 15 feet, and front 20 feet leave 80 x 115 = 9,200 square feet.' },
      { key: 'C', label: 'Proposed 7,000-square-foot footprint', x: 15, y: 27, width: 70, height: 100, pattern: 'solid', labelAt: { x: 50, y: 75 }, description: 'It fits within B, but exceeds the separately stipulated 40% coverage ceiling: 15,000 x 0.40 = 6,000 square feet.' },
    ],
    conclusion: 'The proposal fails the stated coverage rule even though its drawn edges fit the setback envelope.',
    caption: 'Original fictional geometry. All local standards and area definitions are assumptions, not California-wide rules or development approval; other constraints are omitted.',
  },
  {
    id: 'exp-ownership-deed-exception-area',
    lessonSlug: 'ownership-legal-descriptions', afterSection: 'subtract-an-exception-in-matching-units',
    title: 'An excepted corner is not conveyed',
    objective: 'Subtract an expressly excluded fee area in matching units and distinguish the result from a mere easement burden.',
    sourceUrls: [descriptions], kind: 'parcel',
    extent: { width: 330, height: 264 }, unit: 'feet',
    areas: [
      { key: 'A', label: 'Outer described tract', x: 0, y: 0, width: 330, height: 264, pattern: 'clear', labelAt: { x: 165, y: 145 }, description: '330 x 264 = 87,120 square feet, or 2 acres.' },
      { key: 'B', label: 'Express fee exception', x: 264, y: 0, width: 66, height: 132, pattern: 'hatch', description: 'The conveyance excludes this 66 x 132 = 8,712-square-foot corner: 0.20 acre.' },
    ],
    conclusion: 'Conveyed area: 2.00 - 0.20 = 1.80 acres. At a stipulated $50,000 per acre, the acreage-based price is $90,000.',
    caption: 'Original fictional plot, not a legal description. Change B to an easement only and this fee-area subtraction is no longer justified by those facts.',
  },
  {
    id: 'exp-ownership-irregular-site-price',
    lessonSlug: 'ownership-legal-descriptions', afterSection: 'area-frontage-and-units',
    title: 'Price a rectangle and triangle without doubling the triangle',
    objective: 'Compute nonoverlapping component areas using perpendicular triangle height, then apply a square-foot price.',
    sourceUrls: [descriptions], kind: 'calculation',
    rows: [
      { label: 'Rectangle: 100 x 50 = 5,000 sq ft, at $12 per sq ft', amount: 60000 },
      { label: 'Triangle: 0.5 x 100 x 30 = 1,500 sq ft, at $12 per sq ft', amount: 18000 },
    ],
    result: { label: 'Indicated area-based price', amount: 78000, detail: 'Total area is 6,500 square feet. The 30 feet is perpendicular height, not an assumed sloping side length.' },
    caption: 'Assume the two shapes are nonoverlapping and the same stipulated price applies to both. This is area arithmetic, not an appraisal or a survey certification.',
  },
  {
    id: 'exp-ownership-independent-height-permissions',
    lessonSlug: 'ownership-land-use-controls', afterSection: 'ownership-operates-within-a-legal-framework',
    title: 'One favorable height limit does not approve the workshop',
    objective: 'Apply concurrent public and enforceable private height limits without asserting that every private restriction is valid.',
    sourceUrls: [code('CIV', '5975')], kind: 'document',
    documentTitle: 'Fictional workshop approval check',
    context: 'Assume these stipulated limits apply, the private restriction is enforceable, and no overriding law displaces it.',
    fields: [
      { label: 'Public height limit', value: '35 feet', annotation: 'The proposed 28-foot workshop clears this one public dimension.' },
      { label: 'Recorded covenant', value: '24 feet', annotation: 'The same proposal exceeds this independently enforceable restriction by four feet.' },
      { label: 'Proposed height', value: '28 feet', annotation: 'Passing 35 feet is not permission to ignore 24 feet.' },
      { label: 'Changed fact', value: 'Private restriction is legally unenforceable', annotation: 'Now reassess the applicable obligations; the phrase stricter always wins is too absolute.' },
    ],
    conclusion: 'Identify which restrictions are valid and applicable before selecting the practical limiting result.',
    caption: 'Original fictional comparison. Neither a local permit nor private approval universally substitutes for the other.',
  },
  {
    id: 'exp-ownership-plan-zoning-construction-records',
    lessonSlug: 'ownership-land-use-controls', afterSection: 'general-plans-zoning-and-building-codes',
    title: 'Three records answer three different project questions',
    objective: 'Distinguish long-term planning policy, current use permission, and construction compliance when evaluating a proposed building.',
    sourceUrls: [code('GOV', '65302')], kind: 'document',
    documentTitle: 'Fictional project research register',
    context: 'The following agency records are stipulated examples, not an actual city determination.',
    fields: [
      { label: 'General-plan policy', value: 'Neighborhood-serving development encouraged', annotation: 'A policy direction is not an issued permit for this specific shop.' },
      { label: 'Zoning determination', value: 'Proposed shop use permitted', annotation: 'This addresses the stated use; it does not certify the building design.' },
      { label: 'Building review', value: 'Required fire-egress design unresolved', annotation: 'Use permission does not eliminate the separate construction issue.' },
    ],
    conclusion: 'The site may support the use in principle while the submitted construction still needs correction.',
    caption: 'Original instructional register. Actual city rules, state-law overrides, permit conditions, and project approvals require verification.',
  },
  {
    id: 'exp-ownership-density-capacity-bottleneck',
    lessonSlug: 'ownership-land-use-controls', afterSection: 'read-density-and-intensity-as-separate-constraints',
    title: 'A density calculation is a ceiling, not a site plan',
    objective: 'Compute a stipulated density limit and recognize a lower independent project constraint.',
    sourceUrls: [code('GOV', '65302')], kind: 'document',
    documentTitle: 'Fictional development capacity worksheet',
    context: 'All figures are exercise assumptions. No state density bonus, exception, or other rule changes them.',
    fields: [
      { label: 'Counted site area', value: '3 acres', annotation: 'Use the area defined by the stipulated density rule, not an assumed buildable-area substitute.' },
      { label: 'Density limit', value: '6 units per acre', annotation: '3 x 6 gives an 18-unit ceiling under this rule alone.' },
      { label: 'Independent infrastructure constraint', value: 'Capacity for 12 units', annotation: 'Assume this is an applicable binding limit for the exercise.' },
      { label: 'Combined ceiling', value: 'At most 12 units under these two limits', annotation: 'Satisfying the tighter number still does not prove every other approval requirement.' },
    ],
    conclusion: 'Eighteen is the density answer; twelve is the combined ceiling in the stated case. Neither is an approval certificate.',
    caption: 'Original arithmetic worksheet. There is no universal California six-unit-per-acre or twelve-unit infrastructure rule.',
  },
  {
    id: 'exp-ownership-far-versus-footprint',
    lessonSlug: 'ownership-land-use-controls', afterSection: 'read-density-and-intensity-as-separate-constraints',
    title: 'Stacking another floor changes floor area, not the footprint',
    objective: 'Apply a stipulated floor-area ratio across multiple stories instead of applying the allowable total independently to each floor.',
    sourceUrls: [code('GOV', '65302')], kind: 'parcel',
    extent: { width: 200, height: 100 }, unit: 'feet',
    areas: [
      { key: 'A', label: '20,000-square-foot lot', x: 0, y: 0, width: 200, height: 100, pattern: 'clear', labelAt: { x: 155, y: 50 }, description: 'Assume counted lot area is 200 x 100 = 20,000 square feet and FAR is 0.50: 10,000 square feet of total counted floor area.' },
      { key: 'B', label: '4,000-square-foot building footprint', x: 20, y: 25, width: 80, height: 50, pattern: 'solid', description: 'Each full story contains 80 x 50 = 4,000 counted square feet under the stated definitions.' },
    ],
    conclusion: 'Two full stories total 8,000 square feet; three total 12,000 and exceed the 10,000-square-foot FAR limit even with the same footprint.',
    caption: 'Original fictional top-down plan. FAR, counting definitions, and dimensions are assumed; height, setbacks, coverage, and other constraints are not determined by this one calculation.',
  },
  {
    id: 'exp-ownership-variance-property-not-profit',
    lessonSlug: 'ownership-land-use-controls', afterSection: 'compare-three-different-approval-paths',
    title: 'The hardship must concern the property and statutory findings',
    objective: 'Distinguish a potential dimensional variance from personal economic preference and an otherwise prohibited use.',
    sourceUrls: [code('GOV', '65906')], kind: 'decision',
    question: 'What fact supports, or defeats, the proposed variance analysis under the ordinary California statute?',
    branches: [
      { label: 'Unusual terrain disadvantages this parcel', detail: 'Compare similarly zoned nearby properties and the effect of strict dimensional compliance.', outcome: 'Potential variance analysis, if every required finding can actually be supported.' },
      { label: 'A larger building would earn more rent', detail: 'No qualifying property-specific disparity is established.', outcome: 'Profit preference alone does not supply the statutory findings.' },
      { label: 'Retail use is not authorized by the zone', detail: 'The owner labels the prohibited-use request a variance.', outcome: 'The ordinary variance statute does not authorize that use merely by changing the application label.' },
    ],
    caption: 'A conditional use permit concerns a use contemplated conditionally under the applicable zoning framework. It is not the same approval path as a dimensional variance.',
  },
  {
    id: 'exp-ownership-nonconforming-lawful-history',
    lessonSlug: 'ownership-land-use-controls', afterSection: 'relief-and-existing-uses',
    title: 'Age is evidence of history, not proof of lawful history',
    objective: 'Apply a stated local distinction between a lawfully established use made nonconforming by later rules and a use that was illegal from the outset.',
    sourceUrls: ['https://codelibrary.amlegal.com/codes/lapuente/latest/lapuente_ca/0-0-0-39966'], kind: 'timeline',
    premise: 'Use La Puente Municipal Code 10.60.020 as the identified local example. Assume continuing uses and no expansion, abandonment, or rebuilding issue.',
    events: [
      { when: 'Before the zoning change', label: 'Shop A lawfully established', detail: 'Its required use approvals existed under the earlier rules.' },
      { when: 'Same period', label: 'Shop B opened unlawfully', detail: 'Assume its use violated the governing rules and was never legalized.' },
      { when: 'Rules change', label: 'Current rules do not allow either new shop', detail: 'A\'s lawful prior status supports the local nonconforming route; B\'s mere age does not satisfy it.' },
    ],
    conclusion: 'The decisive changed fact is lawful establishment, not how old the storefront looks.',
    caption: 'Original local-code illustration, not a statewide guarantee of continued use. Each jurisdiction\'s rules and overriding law govern continuation, expansion, and casualty rebuilding.',
  },
  {
    id: 'exp-ownership-four-versus-six-parcels',
    lessonSlug: 'ownership-land-use-controls', afterSection: 'subdivision-and-environmental-review',
    title: 'Below five does not mean below every subdivision rule',
    objective: 'Distinguish local physical-division regulation from the general five-parcel offering threshold without ignoring exclusions or special categories.',
    sourceUrls: [code('GOV', '66424'), code('BPC', '11000'), 'https://www.dre.ca.gov/Developers/'], kind: 'comparison',
    columns: [
      { label: 'Ordinary four-lot division', points: ['Assume an ordinary covered division for sale, with no exemption or special category.', 'Being below the general five-lot Subdivided Lands Law threshold does not remove local Map Act analysis.'] },
      { label: 'Change the proposal to six lots', points: ['The same physical-division inquiry remains.', 'The general five-or-more offering threshold is now also implicated; check actual coverage and public-report requirements.'] },
      { label: 'Different work by different authorities', points: ['Local division approval concerns the land-division process.', 'DRE offering regulation and required buyer information are not construction warranties or investment endorsements.'] },
    ],
    caption: 'Do not extend this simplified lot-count comparison indiscriminately to condominiums, cooperative conversions, undivided-interest offerings, or exempt transactions.',
  },
  {
    id: 'exp-ownership-ceqa-evidence-paths',
    lessonSlug: 'ownership-land-use-controls', afterSection: 'different-environmental-review-outcomes',
    title: 'The evidence determines the environmental review path',
    objective: 'Distinguish a negative declaration, mitigated negative declaration, and EIR for a nonexempt covered project.',
    sourceUrls: [code('PRC', '21080')], kind: 'decision',
    question: 'Assume the project is subject to CEQA and no exemption applies. What does the record establish?',
    branches: [
      { label: 'No substantial evidence of a possible significant effect', detail: 'Apply the governing whole-record standard.', outcome: 'Negative-declaration route; negative does not mean the project was rejected.' },
      { label: 'Qualifying revisions eliminate potential significant effects', detail: 'Required revisions precede public review, with no substantial evidence of a remaining significant effect.', outcome: 'Mitigated-negative-declaration route under the stated conditions.' },
      { label: 'Substantial evidence of a possible significant effect remains', detail: 'The applicable evidence standard is met; unsupported speculation alone is not the test.', outcome: 'Prepare an environmental impact report.' },
    ],
    caption: 'These are review-document paths, not automatic project approvals. CEQA coverage, exemptions, and separate land-use permissions must be evaluated independently.',
  },
  {
    id: 'exp-ownership-riparian-place-of-use',
    lessonSlug: 'ownership-water-environment', afterSection: 'surface-water-and-groundwater',
    title: 'The same owner does not make every field riparian',
    objective: 'Distinguish a qualifying riparian place of use from a separate nonriparian parcel reached by a proposed pipe.',
    sourceUrls: [water], kind: 'parcel',
    extent: { width: 320, height: 160 }, unit: 'schematic',
    areas: [
      { key: 'A', label: 'Qualifying riparian parcel', x: 30, y: 20, width: 100, height: 120, pattern: 'clear', labelAt: { x: 80, y: 95 }, description: 'Assume verified riparian status and otherwise reasonable use on this parcel beside the natural watercourse.' },
      { key: 'B', label: 'Separate nonriparian parcel', x: 220, y: 20, width: 100, height: 120, pattern: 'hatch', labelAt: { x: 270, y: 95 }, description: 'The same owner wants to irrigate this separate field. Assume it has no independent right authorizing this diversion and use.' },
      { key: 'C', label: 'Intervening land', x: 130, y: 20, width: 90, height: 120, pattern: 'clear', labelAt: { x: 175, y: 95 }, description: 'A proposed pipe crossing this land also raises an independent route or access-right question.' },
    ],
    lines: [
      { label: 'Natural watercourse beside A', from: { x: 30, y: 0 }, to: { x: 30, y: 160 }, style: 'solid', labelAt: { x: 30, y: 10 } },
      { label: 'Proposed export pipe to B', from: { x: 30, y: 50 }, to: { x: 270, y: 50 }, style: 'dashed', labelAt: { x: 175, y: 50 } },
    ],
    conclusion: 'A\'s riparian right alone does not establish authority to export to B. A working pipe would prove neither water entitlement nor lawful access across C.',
    caption: 'Original schematic, not a surveyed water-right boundary. Riparian status and authorized place of use are expressly stipulated; geometry alone cannot establish them.',
  },
  {
    id: 'exp-ownership-water-entitlement-supply-budget',
    lessonSlug: 'ownership-water-environment', afterSection: 'separate-entitlement-capacity-and-delivery',
    title: 'A larger pump cannot close a legal or seasonal water gap',
    objective: 'Calculate separate entitlement and supply shortfalls without treating tested pumping capacity as an annual water right.',
    sourceUrls: [water], kind: 'document',
    documentTitle: 'Fictional irrigation feasibility worksheet',
    context: 'All volumes are stipulated annual amounts for the same proposed use; no other supply or legal entitlement is available in this exercise.',
    fields: [
      { label: 'Proposed demand', value: '60 acre-feet', annotation: 'The irrigation plan requires this annual volume under the stated assumptions.' },
      { label: 'Authorized amount', value: '45 acre-feet under the stated right', annotation: 'Demand exceeds this amount by 60 - 45 = 15 acre-feet.' },
      { label: 'Available seasonal supply', value: '35 acre-feet', annotation: 'Even the stated 45-acre-foot entitlement does not create water that is unavailable. Supply falls 25 acre-feet short of demand.' },
      { label: 'Pump test', value: 'Higher mechanical delivery capacity', annotation: 'A rate test is not an annual entitlement or a drought-supply guarantee.' },
    ],
    conclusion: 'Fifteen acre-feet is the entitlement gap; twenty-five is the stated supply gap. Do not add them as independent water deliveries.',
    caption: 'Original planning exercise, not a water allocation or agricultural recommendation. The legality and reliability of any substitute supply must be established separately.',
  },
  {
    id: 'exp-ownership-well-records-three-questions',
    lessonSlug: 'ownership-water-environment', afterSection: 'a-water-source-is-not-a-complete-water-right',
    title: 'A working well answers only one part of due diligence',
    objective: 'Separate physical pumping evidence, the legal basis of groundwater use, and applicable basin management requirements.',
    sourceUrls: [water, 'https://water.ca.gov/Programs/Groundwater-Management/SGMA-Groundwater-Management'], kind: 'comparison',
    columns: [
      { label: 'Well test', points: ['Shows measured performance under the test conditions.', 'Does not itself establish an unlimited extraction right or future drought yield.'] },
      { label: 'Use-right analysis', points: ['Identify overlying use, any adjudication, and other relevant entitlement facts.', 'Ownership above a basin does not justify ignoring other owners or applicable limits.'] },
      { label: 'Basin management file', points: ['Check the applicable GSA, plan, allocation, and reporting rules for the actual basin.', 'SGMA does not convert every ordinary groundwater well into a surface-water permit application.'] },
    ],
    caption: 'A missing State Water Board surface-water permit is not the same finding as missing all lawful groundwater authority. Classify the water and the applicable framework first.',
  },
  {
    id: 'exp-ownership-accretion-existing-right-of-way',
    lessonSlug: 'ownership-water-environment', afterSection: 'why-the-cause-and-pace-of-shoreline-change-matter',
    title: 'New natural bank land does not erase an existing right-of-way',
    objective: 'Apply the natural gradual bank-formation rule with its existing-right-of-way qualification and distinguish artificial fill.',
    sourceUrls: [code('CIV', '1014'), 'https://www.slc.ca.gov/public-trust/'], kind: 'document',
    documentTitle: 'Fictional riverbank history file',
    context: 'Assume a riverbank case governed by CIV 1014, with natural imperceptible formation, an established bank owner, and no competing boundary or public-trust issue changing the result.',
    fields: [
      { label: 'Formation history', value: 'Natural deposits accumulate gradually', annotation: 'The origin and pace fit the stated statutory premise; a recent photograph alone would not establish them.' },
      { label: 'Bank ownership', value: 'Verified title of the adjoining bank owner', annotation: 'Identify the legally relevant bank owner before assigning the added land.' },
      { label: 'Existing passage right', value: 'Established right-of-way over the bank', annotation: 'The statutory addition is subject to an existing right-of-way; do not erase that burden.' },
      { label: 'Changed fact', value: 'Owner imported fill instead', annotation: 'Artificial fill does not satisfy this natural-formation premise or prove new title.' },
    ],
    conclusion: 'The stated natural addition can belong to the bank owner while remaining subject to the existing passage right.',
    caption: 'Original evidence exercise. Sudden avulsion, artificial changes, navigable waters, public trust, and actual boundary disputes require their own analysis.',
  },
  {
    id: 'exp-ownership-environmental-indemnity-parties',
    lessonSlug: 'ownership-water-environment', afterSection: 'read-environmental-due-diligence-in-stages',
    title: 'A seller promise and a regulator claim follow different paths',
    objective: 'Distinguish private environmental reimbursement rights from statutory liability and the solvency risk of an indemnitor.',
    sourceUrls: ['https://www.epa.gov/enforcement/superfund-liability', 'https://uscode.house.gov/view.xhtml?req=granuleid:USC-prelim-title42-section9607&num=0&edition=prelim'], kind: 'relationship',
    center: { label: 'Contaminated-site buyer', detail: 'Assume the buyer qualifies as a responsible party, with no applicable defense or protection established.' },
    nodes: [
      { label: 'Regulatory claim', connection: 'statutory liability', detail: 'The governing environmental law determines the buyer\'s exposure; the buyer-seller contract does not bind away that public claim.' },
      { label: 'Seller indemnity', connection: 'private allocation', detail: 'An enforceable indemnity may support reimbursement between the contracting parties.' },
      { label: 'Seller resources', connection: 'collection risk', detail: 'Even a contractual right to payment is not proof that the seller can fund the cleanup or reimburse the buyer.' },
    ],
    caption: 'Conceptual claim map, not a determination of liability. Whether the buyer is a responsible party and whether a statutory protection applies must be evaluated before using this assumed case.',
  },
  {
    id: 'exp-ownership-bfpp-before-and-after-closing',
    lessonSlug: 'ownership-water-environment', afterSection: 'purchaser-protection-has-continuing-conditions',
    title: 'Closing is not the end of purchaser-protection duties',
    objective: 'Distinguish pre-acquisition inquiries from continuing obligations when evaluating BFPP protection for known contamination.',
    sourceUrls: ['https://www.epa.gov/enforcement/bona-fide-prospective-purchasers'], kind: 'timeline',
    premise: 'A buyer knowingly considers a contaminated site. BFPP status is only a possibility until all threshold and ongoing criteria are established.',
    events: [
      { when: 'Before acquisition', label: 'Complete qualifying inquiries', detail: 'All appropriate inquiries are a threshold requirement, not merely a report ordered after title passes.' },
      { when: 'At acquisition', label: 'Test all eligibility conditions', detail: 'Knowledge of contamination does not alone defeat BFPP status, but a completed inquiry does not establish every criterion.' },
      { when: 'After acquisition', label: 'Exercise appropriate care', detail: 'Continuing obligations include reasonable steps concerning continuing releases and threatened future releases.' },
      { when: 'Conditions change', label: 'Reassess ongoing compliance', detail: 'Do not treat the closing file as a permanent immunity certificate while ignoring later conditions.' },
    ],
    conclusion: 'A qualifying purchase and compliant conduct after closing both matter. A seller indemnity answers a different question.',
    caption: 'Original compliance sequence, not a complete BFPP checklist or a determination that a particular buyer is protected.',
  },
  {
    id: 'exp-ownership-fault-map-wrong-assurance',
    lessonSlug: 'ownership-water-environment', afterSection: 'distinguish-hazard-mapping-from-a-guarantee',
    title: 'A fault-zone answer is not an all-hazards clearance',
    objective: 'Identify the limited hazard addressed by an Alquist-Priolo map and reject unsupported conclusions about different risks.',
    sourceUrls: ['https://www.conservation.ca.gov/cgs/alquist-priolo'], kind: 'document',
    documentTitle: 'Fictional map-review notes',
    context: 'Assume the current map has been correctly matched to the subject parcel. No actual hazard designation is represented.',
    fields: [
      { label: 'Map reviewed', value: 'Alquist-Priolo Earthquake Fault Zone', annotation: 'This framework addresses surface fault rupture, not every earthquake-related hazard.' },
      { label: 'Stated map finding', value: 'Subject outside this mapped zone', annotation: 'Answers this mapped-zone question only.' },
      { label: 'Buyer asks about liquefaction', value: 'Different hazard inquiry', annotation: 'The outside-fault-zone finding does not establish absence of liquefaction or other ground-failure risk.' },
      { label: 'Proposed advertisement', value: 'Earthquake safe', annotation: 'The reviewed evidence does not support this broad assurance.' },
    ],
    conclusion: 'Name the map, the parcel, and the hazard actually assessed before making a property claim.',
    caption: 'Original instructional record. Site-specific investigation, other maps, disclosure, insurance, and construction requirements remain distinct.',
  },
  {
    id: 'exp-ownership-special-land-project-file',
    lessonSlug: 'ownership-water-environment', afterSection: 'evaluate-special-land-restrictions',
    title: 'The buyer\'s new plan needs its own authority',
    objective: 'Identify the relevant independent restriction when a buyer proposes a new coastal, agricultural, or waterfront use.',
    sourceUrls: ['https://www.coastal.ca.gov/whoweare.html', 'https://www.conservation.ca.gov/dlrp/wa', 'https://www.slc.ca.gov/public-trust/'], kind: 'decision',
    question: 'Which new proposal requires more than proof that the seller already owns or uses the land?',
    branches: [
      { label: 'Replace a coastal house with a larger one', detail: 'An existing house is evidence of historical use, not automatic permission for the replacement.', outcome: 'Check applicable coastal and local development authority for the actual proposed work.' },
      { label: 'Subdivide land under a Williamson Act contract', detail: 'Assume the contract remains in effect and the proposed residential use conflicts with its restrictions.', outcome: 'The purchase does not itself cancel the contractual land-use limitation.' },
      { label: 'Exclude all public use beside waterfront land', detail: 'A waterfront deed does not settle every nearby public-trust boundary or use right.', outcome: 'Investigate the actual title, boundaries, grants, and public-trust interests.' },
    ],
    caption: 'Original changed-project cases. These restrictions need not transfer fee ownership to the agency, and no blanket coastal exemption or contract-termination period is assumed.',
  },
]
