export const questionConcepts = [
  { id: 'property-classification', label: 'Real and personal property' },
  { id: 'fixtures', label: 'Fixtures and removal rights' },
  { id: 'ownership-estates', label: 'Estates and duration of ownership' },
  { id: 'co-ownership', label: 'Co-ownership and title' },
  { id: 'land-descriptions', label: 'Legal descriptions and land measurement' },
  { id: 'easements', label: 'Easement creation and use' },
  { id: 'liens-and-encumbrances', label: 'Liens and other encumbrances' },
  { id: 'land-use-powers', label: 'Government land-use powers' },
  { id: 'land-use-approvals', label: 'Land-use approvals and restrictions' },
  { id: 'subdivision-regulation', label: 'Subdivision regulation' },
  { id: 'water-rights', label: 'Water rights' },
  { id: 'environmental-liability', label: 'Environmental liability' },
  { id: 'special-land-restrictions', label: 'Special land restrictions' },
  { id: 'land-characteristics', label: 'Physical and economic characteristics of land' },
  { id: 'agency-authority', label: 'Actual, ostensible and ratified authority' },
  { id: 'agency-disclosure', label: 'Agency disclosure and confirmation' },
  { id: 'dual-agency', label: 'Dual agency and confidentiality' },
  { id: 'agency-conflicts', label: 'Agency conflicts and informed consent' },
  { id: 'broker-compensation', label: 'Broker compensation and referral rules' },
  { id: 'agency-termination', label: 'Agency termination and continuing duties' },
  { id: 'licensing-authority', label: 'Authority to perform licensed work' },
  { id: 'broker-supervision', label: 'Broker supervision' },
  { id: 'consumer-recovery', label: 'Discipline and consumer recovery' },
  { id: 'trust-custody', label: 'Trust fund custody and disbursement' },
  { id: 'trust-reconciliation', label: 'Trust records and reconciliation' },
  { id: 'advertising-accuracy', label: 'Advertising accuracy' },
  { id: 'advertising-identity', label: 'Advertising and brokerage identity' },
  { id: 'digital-images', label: 'Digitally altered property images' },
  { id: 'competition', label: 'Competition and independent pricing' },
  { id: 'digital-security', label: 'Digital records and transaction security' },
  { id: 'contract-remedies', label: 'Contract remedies' },
  { id: 'representation-agreements', label: 'Representation agreements' },
  { id: 'contract-performance', label: 'Contract performance' },
  { id: 'options-and-leases', label: 'Options and lease rights' },
  { id: 'negotiable-instruments', label: 'Negotiable instruments' },
  { id: 'value-concepts', label: 'Price, cost, and value' },
  { id: 'economic-principles', label: 'Appraisal principles' },
  { id: 'highest-best-use', label: 'Highest and best use' },
  { id: 'assemblage', label: 'Assemblage and plottage' },
  { id: 'sales-adjustments', label: 'Comparable-sale adjustments' },
  { id: 'sales-evidence', label: 'Sales evidence and reconciliation' },
  { id: 'cost-approach', label: 'Cost approach' },
  { id: 'appraisal-depreciation', label: 'Depreciation and obsolescence' },
  { id: 'income-capitalization', label: 'Income capitalization' },
  { id: 'income-multipliers', label: 'Gross income multipliers' },
  { id: 'investment-ratios', label: 'Equity returns and debt coverage' },
  { id: 'income-stabilization', label: 'Stabilized income' },
  { id: 'property-tax-basis', label: 'Property tax and basis' },
  { id: 'foreclosure-clock', label: 'Foreclosure deadlines' },
  { id: 'tenancy-notices', label: 'Tenancy notices' },
  { id: 'tds-exemptions', label: 'Transfer Disclosure Statement exemptions' },
  { id: 'fair-housing-exemptions', label: 'Fair housing exemptions' },
  { id: 'bulk-sales', label: 'Bulk sales' },
  { id: 'fiduciary-duties', label: 'Fiduciary duties' },
  { id: 'agency-relationships', label: 'Agency relationships' },
  { id: 'contract-enforceability', label: 'Contract enforceability' },
  { id: 'title-priority', label: 'Title and priority' },
  { id: 'noi-versus-cash-flow', label: 'NOI and cash flow' },
  { id: 'security-deposits', label: 'Security deposits' },
  { id: 'fair-housing-service', label: 'Fair housing and service' },
  { id: 'property-disclosures', label: 'Property disclosures' },
  { id: 'commercial-leases', label: 'Commercial leases' },
  { id: 'environmental-investigation', label: 'Environmental investigation' },
  { id: 'property-management', label: 'Property management' },
  { id: 'financing-ratios', label: 'LTV, DTI, and loan costs' },
  { id: 'loan-amortization', label: 'Amortization and payment structure' },
  { id: 'mortgage-markets', label: 'Primary and secondary mortgage markets' },
  { id: 'loan-programs', label: 'Mortgage programs and assistance' },
  { id: 'adjustable-rate-loans', label: 'Adjustable-rate terms' },
  { id: 'reverse-mortgages', label: 'Reverse mortgage obligations' },
  { id: 'notes-and-security', label: 'Notes and security instruments' },
  { id: 'loan-transfers', label: 'Assumption, subordination, and releases' },
  { id: 'anti-deficiency', label: 'California deficiency protections' },
  { id: 'mortgage-disclosures', label: 'Mortgage disclosures and rescission' },
  { id: 'lending-compliance', label: 'Fair lending, RESPA, and originators' },
  { id: 'deed-transfer', label: 'Deed execution, delivery, and estates' },
  { id: 'title-insurance', label: 'Title reports and coverage' },
  { id: 'escrow-closing', label: 'Escrow authority and closing funds' },
  { id: 'income-tax-gain', label: 'Basis, gain, and home-sale exclusion' },
  { id: 'tax-exchanges', label: 'Like-kind exchanges' },
  { id: 'tax-withholding', label: 'Federal and California withholding' },
  { id: 'closing-prorations', label: 'Transfer taxes and closing prorations' },
  { id: 'probate-sales', label: 'Probate sale authority and overbids' },
  { id: 'estate-transfers', label: 'Inheritance and nonprobate transfers' },
  { id: 'special-transfer-processes', label: 'Partition, condemnation, and tax sales' },
  { id: 'bankruptcy-stay', label: 'Bankruptcy stay and enforcement' },
  { id: 'operation-of-law', label: 'Adverse possession, accretion, and dedication' },
] as const

export const questionMisconceptions = [
  { id: 'wrong-trigger', label: 'Uses the wrong triggering event' },
  { id: 'wrong-clock', label: 'Uses the wrong deadline or day count' },
  { id: 'missing-condition', label: 'Omits a required condition' },
  { id: 'wrong-exception', label: 'Applies an unavailable exception' },
  { id: 'role-confusion', label: 'Confuses the parties or their roles' },
  { id: 'misclassification', label: 'Classifies the property or transaction incorrectly' },
  { id: 'wrong-base', label: 'Calculates from the wrong amount' },
  { id: 'wrong-formula', label: 'Uses the wrong calculation' },
  { id: 'reversed-adjustment', label: 'Reverses the direction of an adjustment' },
  { id: 'federal-state-confusion', label: 'Confuses federal and California rules' },
  { id: 'unsupported-inference', label: 'Draws a conclusion the facts do not support' },
  { id: 'remedy-confusion', label: 'Selects a remedy that does not follow' },
  { id: 'duty-confusion', label: 'Confuses the scope or recipient of a duty' },
  { id: 'document-effect', label: 'Gives a document the wrong legal effect' },
  { id: 'source-of-authority', label: 'Relies on the wrong source of authority' },
  { id: 'recall-confusion', label: 'Confuses neighboring definitions or rules' },
] as const
